### ISSUE TITLE
flink消费kafka数据，source端提前更新offset问题

### ISSUE THREAD

**Issue by JasonChoi27** [JasonChoi27/works#2]
### 背景
线上任务开启了checkpoint机制，flink在消费kafka数据时，下游数据处理缓慢，发现source端更新的offset远大于下游消费的offset，当任务失败时，job重启会丢失数据。

### 排查
flink版本：1.2
kakfa版本：0.8.2
job：KafkaSource(p = 1)->rebalance->map(p = 2)->KafkaSink
#### 怀疑一
> task之间有shuffle，是否shuffle缓存了source端的记录，而只有source端做checkpoint，source端消费速度快，导致更zk上的offset也快？

仔细思考，这个怀疑并不成立。
- 只要开启checkpoint机制，每个operator都会调用`AbstractStreamOperator.snapshotState()`方法，只是对于没有实现`CheckpointedFunction`接口的operator，snapshot时什么事情都不做；
- Checkpoint机制是CheckpointCoordinator定时在Source端混入Barrrier并触发Source端的snapshot，随后的operator在接收到Barrier时触发该operator的snapshot，所有operator在snapshot完之后都向CheckpointCoordinator发送StateHandle，CheckpointCoordinator收到所有operator的StateHandle时才认为此次checkpoint完成；
- 对于KafkaSource场景，checkpoint完成之后才向zk更新offset。

#### 怀疑二
> flink的checkpoint机制与KafkaSource内部的offset更新机制冲突了？

翻看代码，确定怀疑成立。
- flink1.2版本中Kafka connector中的Source端会根据`auto.commit.interval.ms`参数起一个定时commit offset的线程，而不管是否开启checkpoint机制，只要这个参数大于0（默认60秒），线程就会启动；
- 对于我们的场景，不管checkpoint是否开启，KafkaConsumer都会60秒更新一次offset；
-  这是Kafka connector在flink1.2版本中的漏洞，1.3版本中修改了逻辑，只要checkpoint机制开启，定期commit线程就不会启动。

### 解决
传入FlinkKafkaConsumer08中的properties添加如下参数：
- auto.commit.enable = false
- auto.commit.interval.ms = -1

问题解决。

**Comment by lynchlee** [comment]
👍
